import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  uploadBookContainer: {
    maxHeight: 730,
    minHeight: 640,
    backgroundColor: "#FFF",
    top: "5%",
    alignItems: "center",
  },
  formContainer: {
    top: "5%",
    height: "100%",
    width: "100%",
  },
  inputText: {
    alignSelf: 'center',
    padding: 10,
    width: '90%',
    height: '5%',
    backgroundColor: '#ECEFF0',
    marginBottom: 10,
    color: "black"
  },
  buttonContainer: {
    top: "10%",
    width: "100%",
    maxWidth: 800,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  imageButton: {
    flexDirection: "row",
    padding: 10,
    alignSelf: "center",
    width: "43%",
    borderColor: "#1C1427",
    borderStyle: "solid",
    borderWidth: 1,
  },
  imageText: {
    margin: 0,
    marginLeft: 20,
    alignSelf: "center",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 15,
    lineHeight: 24,
    color: "#1C1427",
    letterSpacing: 0.15,
  },
  uploadButton: {
    marginLeft: 14,
    padding: 10,
    width: "43%",
    borderRadius: 5,
    backgroundColor: "#DADADA",
  },
  uploadText: {
    margin: 0,
    fontFamily: "Roboto",
    alignSelf: "center",
    fontStyle: "normal",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 15,
    lineHeight: 24,
    color: "#1C1427",
    letterSpacing: 0.15,
  },
  textError: {
    alignSelf: "center",
    marginBottom: 5,
    marginTop: -5,
    color: "red",
  },
});