import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    titleContainer: {
      display: "flex",
      flexDirection: "column",
      alignSelf: "center",
      top: "10%",
    },
    iconContainer: {
      display: "flex",
      flexDirection: "row",
      alignSelf: "center",
    },
    titleText: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: 14,
      letterSpacing: 1.25,
      color: "#1C1427",
      textAlign: "center",
    },
    offerDetailContainer: {
      display: "flex",
      flexDirection: "column",
      alignSelf: "center",
      top: "25%",
    },
    offerText: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: 14,
      letterSpacing: 1.25,
      color: "#1C1427",
      textAlign: "center",
    },
    buttonsContainer: {
      top: "75%",
      width: "100%",
      alignSelf: "center",
      justifyContent: "center",
      display: "flex",
      flexDirection: "row",
    },
    imageButton: {
      padding: 10,
      width: "45%",
      borderColor: "#1C1427",
      borderStyle: "solid",
      borderWidth: 1,
    },
    imageText: {
      alignSelf: "center",
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: 14,
      color: "#1C1427",
      letterSpacing: 0.15,
    },
    uploadButton: {
      marginLeft: 14,
      padding: 10,
      width: "45%",
      borderRadius: 5,
      backgroundColor: "#7ECA9C",
    },
    uploadText: {
      fontFamily: "Roboto",
      alignSelf: "center",
      fontStyle: "normal",
      fontWeight: "bold",
      textAlign: "center",
      fontSize: 14,
      color: "#1C1427",
      letterSpacing: 0.15,
    },
  });